import Head from 'next/head';
import AgeCalculator from '../components/age-calculator';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-screen flex-col  items-center justify-center bg-gradient-to-br from-yellow-100 to-pink-200">
        <div>
          <h1 className="mb-12 text-center text-4xl font-bold text-slate-800 lg:text-5xl">
            Age Calculator
          </h1>

          <AgeCalculator />
        </div>
      </main>
    </div>
  );
}
